### ISSUE TITLE
Random User Picker

### ISSUE THREAD

**Issue by diziara** [MageCity/LongSphinx#71]
Useful for contests and the like. Suggested user commands:

`!random` would return a random user from the server list.
`!random @role` would return a random user from the selected role

To avoid annoying users, perhaps limit it's access to admin users or designated role?

**Comment by MageCity** [comment]
For the record, since I seem to want to confirm this every time I look at this issue: The [server object](https://discordpy.readthedocs.io/en/async/api.html#server) has a list of members, but a [role object](https://discordpy.readthedocs.io/en/async/api.html#role) does not have such a convenience, so I'll have to iterate through the server's list for role-specific selection.

**Comment by diziara** [comment]
Honestly, while the random within the role would be useful, it's less important. Would it be easier to limit it to people in the channel where the command is issued?

**Comment by MageCity** [comment]
@diziara does the `!pick` command fulfill this request?

**Comment by diziara** [comment]
> @diziara does the `!pick` command fulfill this request?

yes
